const WINDY_LEVELS_SUPPORT_PARAMETERS = [ //Other paramater will be 'surface' as default
'wind', 'dewpoint', 'temp', 'gh', 'rh'
];
const WINDY_PARAMETERS = [
{
  parameter: "temp",
  respKey: ["temp-[level]"],
  desc: "Air temperature"
},
{
  parameter: "dewpoint",
  respKey: ["dewpoint-[level]"],
  desc: "The temperature of dew point, i.e. at which temperature the air reaches 100% humidity."
},
{
  parameter: "precip",
  respKey: ["past3hprecip-surface"],
  desc: "The overall accumulation of all precipitation (water column) for the preceding 3 hours, including snowPrecip and convPrecip (see below)."
},
{
  parameter: "snowPrecip",
  respKey: ["past3hsnowprecip-surface"],
  desc: "The overall snowfall (water column) for the preceding 3 hours."
},
{
  parameter: "convPrecip",
  respKey: ["past3hconvprecip-surface"],
  desc: "The overall precipitation caused by convection (water column) for the preceding 3 hours."
},
{
  parameter: "wind",
  respKey: ["wind_u-[level]", "wind_v-[level]"],
  desc: "Wind speed and direction defined by a two-dimensional vector. The component <code>u</code> defines the speed of a wind blowing from the West towards the East (a negative value therefore implies the opposite direction). The component <code>v</code> similarly defines the speed of a wind blowing from the South towards the North."
},
{
  parameter: "windGust",
  respKey: ["gust-surface"],
  desc: "The speed of wind at gusts."
},
{
  parameter: "cape",
  respKey: ["cape-surface"],
  desc: "Convective available potential energy."
},
{
  parameter: "ptype",
  respKey: ["ptype-surface"],
  desc: "Precipitation type. The value is an integer representing the following types: <ul> <li><strong>0</strong> - No precipitation</li> <li><strong>1</strong> - Rain</li> <li><strong>5</strong> - Snow</li> <li><strong>6</strong> - Wet snow (i.e. starting to melt)<br><small>only GFS</small></li> <li><strong>7</strong> - Mixture of rain and snow<br><small>only AROME and ICON EU</small> </li> </ul>"
},
{
  parameter: "lclouds",
  respKey: ["lclouds-surface"],
  desc: "Low clouds at levels with air pressure above 800hPa The value describes the overall cloud coverage."
},
{
  parameter: "mclouds",
  respKey: ["mclouds-surface"],
  desc: "Medium clouds at levels with air pressure between 450hPa and 800hPa. The value describes the overall cloud coverage."
},
{
  parameter: "hclouds",
  respKey: ["hclouds-surface"],
  desc: "High clouds at levels with air pressure below 450hPa. The value describes the overall cloud coverage."
},
{
  parameter: "rh",
  respKey: ["rh-[level]"],
  desc: "Relative humidity of air."
},
{
  parameter: "gh",
  respKey: ["gh-[level]"],
  desc: "Geopotential height. Signifies at which altitude there is a given air pressure level."
},
{
  parameter: "pressure",
  respKey: ["pressure-surface"],
  desc: "Air pressure."
},
{
  parameter: "waves",
  respKey: ["waves_height-surface", "waves_period-surface", "waves_direction-surface"],
  desc: "The waves’ height, period and direction. The direction defines where the waves come from. The period defines the time interval between arrival of consecutive crests at a stationary point."
},
{
  parameter: "windWaves",
  respKey: ["wwaves_height-surface", "wwaves_period-surface", "wwaves_direction-surface"],
  desc: "The wind waves’ height, period and direction. Wind waves, or wind-generated waves, are surface waves that occur on the free surface of bodies of water (like oceans, seas, lakes, etc.). They result from the wind blowing over an area of water surface. Wind waves are generated by the immediate local wind – which gives them the direction. After the wind ceases to blow, wind waves are called swells. The direction defines where the waves come from. The period defines the time interval between arrival of consecutive crests at a stationary point."
},
{
  parameter: "swell1",
  respKey: ["swell1_height-surface", "swell1_period-surface", "swell1_direction-surface"],
  desc: "The height, period and direction of the waves’ swell. The waves had been created by wind in another area and are not created by local winds. The direction defines where the waves come from (0 = North, 90 = East, 180 = South, 270 = West). The period defines the time interval between arrival of consecutive crests at a stationary point."
},
{
  parameter: "swell2",
  respKey: ["swell2_height-surface", "swell2_period-surface", "swell2_direction-surface"],
  desc: "The height, period and direction of the waves’ swell. Similar to swell1, but the waves are of smaller sizes and come from a different area. The direction defines where the waves come from (0 = North, 90 = East, 180 = South, 270 = West). The period defines the time interval between arrival of consecutive crests at a stationary point."
},
{
  parameter: "so2sm",
  respKey: ["chem_so2sm-surface"],
  desc: "Sulfur dioxide is released naturally by volcanic activity and is produced as a by-product of the burning of fossil fuels contaminated with sulfur compounds."
},
{
  parameter: "dustsm",
  respKey: ["chem_dustsm-surface"],
  desc: "Dust particles in the atmosphere that come from various sources such as soil, dust lifted by weather, volcanic eruptions, and air pollution."
},
{
  parameter: "cosc",
  respKey: ["chem_cosc-surface"],
  desc: "The level of carbon monoxide concentrationin the troposphere."
}
];

const ALL_DBFIELDS = [
  'temp-surface',
  'temp-150h',
  'temp-200h',
  'temp-300h',
  'temp-400h',
  'temp-500h',
  'temp-600h',
  'temp-700h',
  'temp-800h',
  'temp-850h',
  'temp-900h',
  'temp-925h',
  'temp-950h',
  'temp-1000h',
  'dewpoint-surface',
  'dewpoint-150h',
  'dewpoint-200h',
  'dewpoint-300h',
  'dewpoint-400h',
  'dewpoint-500h',
  'dewpoint-600h',
  'dewpoint-700h',
  'dewpoint-800h',
  'dewpoint-850h',
  'dewpoint-900h',
  'dewpoint-925h',
  'dewpoint-950h',
  'dewpoint-1000h',
  'past3hprecip-surface',
  'past3hconvprecip-surface',
  'past3hsnowprecip-surface',
  'wind_u-surface',
  'wind_u-150h',
  'wind_u-200h',
  'wind_u-300h',
  'wind_u-400h',
  'wind_u-500h',
  'wind_u-600h',
  'wind_u-700h',
  'wind_u-800h',
  'wind_u-850h',
  'wind_u-900h',
  'wind_u-925h',
  'wind_u-950h',
  'wind_u-1000h',
  'wind_v-surface',
  'wind_v-150h',
  'wind_v-200h',
  'wind_v-300h',
  'wind_v-400h',
  'wind_v-500h',
  'wind_v-600h',
  'wind_v-700h',
  'wind_v-800h',
  'wind_v-850h',
  'wind_v-900h',
  'wind_v-925h',
  'wind_v-950h',
  'wind_v-1000h',
  'gust-surface',
  'cape-surface',
  'ptype-surface',
  'lclouds-surface',
  'mclouds-surface',
  'hclouds-surface',
  'rh-surface',
  'rh-150h',
  'rh-200h',
  'rh-300h',
  'rh-400h',
  'rh-500h',
  'rh-600h',
  'rh-700h',
  'rh-800h',
  'rh-850h',
  'rh-900h',
  'rh-925h',
  'rh-950h',
  'rh-1000h',
  'gh-surface',
  'gh-150h',
  'gh-200h',
  'gh-300h',
  'gh-400h',
  'gh-500h',
  'gh-600h',
  'gh-700h',
  'gh-800h',
  'gh-850h',
  'gh-900h',
  'gh-925h',
  'gh-950h',
  'gh-1000h',
  'pressure-surface',
];

exports.WINDY_LEVELS_SUPPORT_PARAMETERS = WINDY_LEVELS_SUPPORT_PARAMETERS;
exports.WINDY_PARAMETERS = WINDY_PARAMETERS;
exports.ALL_DBFIELDS = ALL_DBFIELDS;
